import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import SocialMediaIcons from "@/components/ui/social-media";
import { FloatingNavMain } from "@/components/floating-nav-main";

const roboto = Roboto({ subsets: ["latin"], weight: ["400", "500", "700"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body
        className={`${roboto.className} relative min-h-screen bg-bg_primary text-white`}
      >
        <FloatingNavMain />
        <SocialMediaIcons />
        {children}
      </body>
    </html>
  );
}
